### ISSUE TITLE
Is the repo ready to use?

### ISSUE THREAD

**Issue by syomantak** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#1]
Sorry for the silly question, but since I see the initial commit is about 24 hours old, I am asking if the repo is ready to be used. I want to train it on MNIST dataset for an unrelated experiment.

**Comment by SayedNadim** [comment]
Hi,
Yes. The code is ready to use. If you need any help regarding the codes, please feel free to give me a knock. 
Happy coding!
