### ISSUE TITLE
the hole and valid region in mask

### ISSUE THREAD

**Issue by ray0809** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#12]
Hi, when I read the trainer.py 
It means the hole region is 1, and valid region is 0
https://github.com/SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting/blob/0b7eec3154bed9c646e18b77570d520efeb9f9ab/scripts/trainer.py#L40

During calculating L1 loss, you only considered on the valid region
https://github.com/SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting/blob/0b7eec3154bed9c646e18b77570d520efeb9f9ab/scripts/trainer.py#L51

**Comment by SayedNadim** [comment]
Hi,
Sorry for the late reply.
I used l1 to reconstruct the valid region as it is indeed a reconstruction loss. In other papers, different reconstruction losses are used for valid and hole region. In our case, we simply used the valid region loss while incorporating ssim loss for structural reconstruction and gan loss for synthetic content generation.
Thanks for the question.
Cheers!

**Comment by ray0809** [comment]
Hi, 
I get it, Thanks for your reply
