### ISSUE TITLE
refactoring release

### ISSUE THREAD

**Issue by Vozf** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#17]
In readme it is said that refactoring is in process. 2 months have passed since the last update. Is there any estimate date for a release? Is refactoring still on-going? Thanks

**Comment by SayedNadim** [comment]
Hi,
Sorry for being late. I was busy with my other work.
Please check the "sensor_branch" for pre-trained weights for Places2.
Cheers!
