### ISSUE TITLE
could you please tell me why report this error？

### ISSUE THREAD

**Issue by tan990701** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#19]
![图片](https://user-images.githubusercontent.com/52628708/158553725-02a75ef1-971c-4a2b-8725-c076f6d2f64c.png)
![图片](https://user-images.githubusercontent.com/52628708/158553833-e0856811-75a1-4481-a155-dd81f2ae3a9e.png)
train.py

**Comment by SayedNadim** [comment]
Hi,
Can you please tell me in detail how you faced this problem?
Thanks.

**Comment by tan990701** [comment]
hi，I have solved this problem.
size of input tensor and input format are different.The solution is replace add_images with replace_images（plural）
In addition to，could you please share your complete test.py？
thank u very much！

**Comment by SayedNadim** [comment]
Hi  sorry for the late reply. I have used the test loop file for testing. You can modify it for your needs. Let me know if I can help. Thanks.

**Comment by tan990701** [comment]
Hi,I am so sorry to excuse you again.I still have another question.

Q1:In train.py, Why you using random_crop to pre-processed images?Using random_crop will generate incomplete images,Will affect the results of the experiment?

Q2: And if I set configs[random_crop] is False,the program will perform this step:(dataset_loader.py line33)
![QQ截图20220320170927](https://user-images.githubusercontent.com/52628708/159155646-555da6b2-ee11-47e8-b637-04cd2e31aff3.png)

if this line of code is unnecessary?
Looking forward to your reply!Thanks!

**Comment by SayedNadim** [comment]
Hi, thanks for your queries. 

Q1. I think random crop will not degrade perform in case of natural scenes such as ImageNet or Places. But it may degrade in face datasets. In case of natural scenes, we try to maintain structure and texture with the background,  so random_crop will not cause much problems, I think., Depending on the datasets and tasks, it's upto you how to approach this issue.

Q2. You can comment out the line if you want to remove random crop.

Let me know if I can help.
Thanks.

**Comment by tan990701** [comment]
You have answered my doubts. Thank you very much！

**Comment by SayedNadim** [comment]
Feel free to close the issue if your problems are resolved. Thanks.
