### ISSUE TITLE
In test_loop.py probelms

### ISSUE THREAD

**Issue by tan990701** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#20]
![图片](https://user-images.githubusercontent.com/52628708/159423737-160b05d8-548a-4461-a531-6b1a027836dd.png)
![图片](https://user-images.githubusercontent.com/52628708/159423925-86ca2b8b-e1df-43fb-9f3a-e257f7018031.png)
when i run test_loop.py，Why is this error reported？And I find your following code not use “inpainted_result_cpu”again？
What is the function of these three lines of code？Will it make any difference if I annotate it？I hope you can answer my doubts，moreover，could you please release your  test_bbox, and random_bbox.py thanks!

**Comment by SayedNadim** [comment]
Hi,

- You can comment out the line. I used it to normalize the image into [0-255] range. Please refer to the 'sensor' branch for the test file.
- I have updated the codebase earlier. Please refer to the "sensors" branch for the reproducibility of the results. 
- In the case of free-form inpainting, we don't use the bbox function, it was used while I was trying with rectangular masks. 
If you still need to bbox function, I will be happy to help.

Thanks.

**Comment by tan990701** [comment]
sorry， I run the train.py，but performance of train is not well（I didn't modify configs）.I used celebA_HQ as dataset，When the mask is on the face，The  results of inpainting is too bad.And value of loss 
seems went wrong.
![图片](https://user-images.githubusercontent.com/52628708/159612584-b2f54977-a0ef-4752-b918-6658dea87f5e.png)
![图片](https://user-images.githubusercontent.com/52628708/159612610-7cb443f5-416b-4200-81e4-90f065148c3c.png)
![图片](https://user-images.githubusercontent.com/52628708/159612629-2d3bb161-5f13-43bd-a0b1-d22934cc6db6.png)
![图片](https://user-images.githubusercontent.com/52628708/159612674-4e94a591-05b2-42c7-b3ff-e03ba0a5bd96.png)
![图片](https://user-images.githubusercontent.com/52628708/159612741-38fd8eaa-33f7-45e6-b420-f5844e88e092.png)
Thank you for answering my questions！

**Comment by SayedNadim** [comment]
Hi,
I am sorry that you are facing this problem.
Can you please try the 'sensors' branch? 
Thanks.
![Screenshot from 2022-03-24 04-27-09](https://user-images.githubusercontent.com/11741497/159780356-6d37c0a5-6160-4f6a-8fb3-69b3d253b439.png)

**Comment by tan990701** [comment]
Hi,I am sorry to bother you again.I tried the 'sensors' branch，and the rusult is better than ’master‘ branch.And I compared with two pieces of code, not  much difference was found.but why the performance difference?
