### ISSUE TITLE
"sensor"branch problem

### ISSUE THREAD

**Issue by tan990701** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#21]
hi,I found code of "sensor" branch have better effect than "master" branch,but in test rusult,
![微信图片_20220407095503](https://user-images.githubusercontent.com/52628708/162104766-4b6564ed-6a9f-4402-bc55-7169e5bbba51.jpg)
=
![微信图片_20220407095509](https://user-images.githubusercontent.com/52628708/162104979-c2f6d58b-d4df-4d2d-a39c-2f1a418f20fe.jpg)

![微信图片_20220407095519](https://user-images.githubusercontent.com/52628708/162104996-dc4d25be-098f-442f-97cf-259602afed5f.png)

the first picture is coarse inpainting result,the second picture is fine inpainting result,the last picture is mask,

Why does the result of fine inpainting appear outline of mask? 
thanks!

**Comment by SayedNadim** [comment]
Hi, sorry for the late reply. 
It is happening because of the mask resize operation. I guess you are using a bilinear resize operation on the mask which is creating interpolated edges. Please make a mask of the same size as the image using the provided script and try. Let me know if I can help you. 
Thanks.

**Comment by tan990701** [comment]
hi，you hava help me.could you please tell me that  using the provided script how to set different mask ratio(30%40%、40%-50%in your paper) ?Thanks!

**Comment by SayedNadim** [comment]
Hi, 
in the code here,
https://github.com/SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting/blob/fe7e1cf54949f70709b2f544328dfdb92544a765/utils/tools.py#L196

You can add something like this:
```
for _ in range(num_stroke): 
    ratio = numpy.count_nonzero(mask) *100/(height*width)
    if ratio> 30:
        break
```
Hope this helps.
Thanks!

**Comment by tan990701** [comment]
I am sorry to bother you again.
Q1:if I require mask ratio between 20 with 30，how to modify the code？I tried but report error.
Q2: I mentioned last time about using a bilinear resize operation on the mask which is creating interpolated edges, I still in doubt that mask image of resize operation(the size is 256*256) look the same with the mask using the provided script but which line of code is the interpolation edges formed.looking forward for your reply!Thanks!

**Comment by SayedNadim** [comment]
Hi, let me answer the questions.

Q1: You can try this code:

```
import math

import numpy as np
import cv2
import torch


def random_mask(height=256,
                width=256,
                max_vertex=10,
                max_stroke=3,
                max_brush_width=40,
                max_length=100):
    mask = np.zeros((height, width))
    max_angle = np.pi
    for mn in range(max_stroke):
        num_vertex = int(np.random.uniform(max_vertex // 3, max_vertex))
        start_x = int(np.random.uniform(0, height))
        start_y = int(np.random.uniform(0, width))

        for step in range(0, num_vertex):
            angle = np.random.uniform(0, max_angle)

            if step % 2 == 0:
                # Reverse mode
                angle = 2 * math.pi - angle

            length = np.random.uniform(10, max_length)
            brush_width = int(np.random.uniform(max_brush_width / 4, max_brush_width))

            end_x = int(start_x + length * math.sin(angle))
            end_y = int(start_y + length * math.cos(angle))

            cv2.line(mask, (start_y, start_x), (end_y, end_x), 1, brush_width)

            start_x = end_x
            start_y = end_y

            # cv2.circle(mask, (447, 63), brush_width // 4, 255, -1)
        # mask = mask // 255
    return mask.astype(np.float32) * 255

def mask_ratio(mask):
    height, width = mask.shape
    non_zero_values = np.count_nonzero(mask)
    ratio = non_zero_values*100/(height*width)
    return ratio

if __name__ == '__main__':
    save_dir = '/home/la-belva/code_ground/mask_20_30'
    number_of_masks = 100
    count_mask = 0
    while count_mask<number_of_masks:
        mask = random_mask(height=256,
                width=256,
                max_vertex=10,
                max_stroke=3,
                max_brush_width=40,
                max_length=30)
        mr = mask_ratio(mask)
        if 20<mr<30:
            cv2.imwrite(save_dir + '/' + f'mask_20_30_{count_mask}.png',mask)
            count_mask +=1
        else:
            continue
```

Q2: You can comment out this line and check the results. Let me know if you still face problems.
https://github.com/SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting/blob/fe7e1cf54949f70709b2f544328dfdb92544a765/test.py#L62

Let me know if I can help.
Thanks!

**Comment by tan990701** [comment]
hi,I am grateful for your help.I tried to comment out this line.Then,the progress reported error.
RuntimeError: The size of tensor a (256) must match the size of tensor b (1024) at non-singleton dimension 2
because size of mask is unmatched.(my original mask is rectangle).So how to solve this problem.looking forward for your reply!Thanks!

**Comment by tan990701** [comment]
hi,I am grateful for your help.I tried to comment out this line.Then,the progress reported error.
RuntimeError: The size of tensor a (256) must match the size of tensor b (1024) at non-singleton dimension 2
because size of mask is unmatched.(my original mask is rectangle).
But I know why appear outline of mask，the first picture is the result(x = x * (1. - mask)) by using the provided script,the second picture generate black edges(using my own mask).So,I wonder if there is something wrong with composition of mask and the original image?
![图片](https://user-images.githubusercontent.com/52628708/163666340-1d6c43b3-401b-4a48-9485-3ce39749c488.png)
![图片](https://user-images.githubusercontent.com/52628708/163666524-428ade75-cb8e-4bb1-ba49-49498e887a1d.png)

Looking forward for your reply!Thanks!
