### ISSUE TITLE
how to select optimum value?

### ISSUE THREAD

**Issue by superlittl** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#23]
Hi,in your paper,using some losses,but I am confused that how to select optimum value by  focusing on losses.Thanks!

**Comment by SayedNadim** [comment]
Hi,
For finding the optimum values, you can perform hyperparameter search using pytorch ray, bayesian optimization etc. In my paper, I used population-based hyperparameter search using ray to find the optimum values. 
Please let me know if you need any assistance. 
Thanks.

**Comment by superlittl** [comment]
Hi,
Thanks for your reply.Could you provide the code of validation?
![图片](https://user-images.githubusercontent.com/105760324/169281875-41994961-e332-489f-b23a-3009d48339a6.png)
Thanks!

**Comment by SayedNadim** [comment]
Sure. I will provide once I am available to work on next Tuesday. I am on vacation right now. Cheers!

**Comment by superlittl** [comment]
I am all gratitude！

**Comment by SayedNadim** [comment]
Hi, I am sorry for the late reply. I will update the code tomorrow (May 28). Thanks for the wait. Cheers!

**Comment by superlittl** [comment]
Thanks again.

**Comment by superlittl** [comment]
Hi,I am sorry to bother you again.May I ask whether the code has been updated.Thanks！

**Comment by superlittl** [comment]
Hi,could you update the code?Thanks!
