### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by ghost** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#5]
Great work, really looking forwards to giving this a try. Would you mind adding a license file please?

**Comment by SayedNadim** [comment]
Hi,
Thanks for the suggestion. I will surely add a license.
Cheers!

**Comment by SayedNadim** [comment]
Added license. Thanks!

**Comment by yaysummeriscoming** [comment]
Thanks, any chance you could make it MIT or Apache 2.0 please? CC BY NC 4.0 is a bit cumbersome

**Comment by SayedNadim** [comment]
Hi,
We have not decided on the license yet. The code is still in version 1. We will update the license soon. Thanks!
