### ISSUE TITLE
Resuming Training

### ISSUE THREAD

**Issue by syomantak** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#7]
Hey
I feel there is a typo [here](https://github.com/SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting/blob/master/train.py/#L87). I think it  should be  
```start_iteration = trainer_module.resume(checkpoint_path, args.iteration) if config['resume'] else 1``` 
I am getting error on resuming as save and resume paths differ.

**Comment by CyanideBoy** [comment]
Hey nevermind, my bad

**Comment by SayedNadim** [comment]
Hi,
If you're not facing any issue with resuming the training, please close the issue.
Cheers!
