### ISSUE TITLE
Test script error

### ISSUE THREAD

**Issue by syomantak** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#8]
Hey,
There seems to be an import error on the test script [here](https://github.com/SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting/blob/master/test_single.py/#L12). `test_bbox` is not there in utils.tools.

**Comment by SayedNadim** [comment]
Hi,
Thanks for pointing out the typo. `test_bbox` was used to test the box mask. It's not important for the free-form mask. I have updated the code. Let me know if you face anything else.
Cheers!
