### ISSUE TITLE
Trained weights

### ISSUE THREAD

**Issue by ofirkris** [SayedNadim/Global-and-Local-Attention-Based-Free-Form-Image-Inpainting#9]
Hi, great work! 
can you share your trained weights?

**Comment by SayedNadim** [comment]
Hi,
I will upload the weights soon (hopefully within this week)!
Cheers!

**Comment by ofirkris** [comment]
Thanks, can you point me to them?

**Comment by SayedNadim** [comment]
Hi, sorry for late reply. I was busy with other work. I will upload the pretrained model soon. Thanks for the reminder. 
Cheers!

**Comment by JiekeW** [comment]
@SayedNadim I'm very sorry, but the pretrained model will be helpful to me. Thank you very much!

**Comment by junedgar** [comment]
Waiting the pretrained model online!

**Comment by hyolee1999** [comment]
waiting for  pretrained model

**Comment by SoikatHasanAhmed** [comment]
waiting for pretrained weights

**Comment by roimulia2** [comment]
Waiting for the pre-trained model, any news?

**Comment by SayedNadim** [comment]
Hi,
Sorry for being late. I was busy with my "other" work.
Please check the "sensor_branch" for pre-trained weights for Places2.
Cheers!
